### PR TITLE
feat: add new function to list outdated packages

### PR DESCRIPTION
**Pull request by danstis**
Added a new function `Get-Updates` which check for outdated Chocolatey, WinGet and PowerShell packages/modules.
It also writes the outdated items to files in `$env:Temp` to be possibly queried in the PS profile to show outdated packages at the start of the terminal.

### CODE REVIEW

**Comment by C-Roche** [comment]
Perform a check to see if WinGet is installed and ignore it if it's not - or send a message back to say WinGet wasn't found..
Output a message for any system that is checked, but has no update, i.e. "Checked Chocolately and no updates are available".

**Comment by danstis** [comment]
> Perform a check to see if WinGet is installed and ignore it if it's not - or send a message back to say WinGet wasn't found..
> Output a message for any system that is checked, but has no update, i.e. "Checked Chocolately and no updates are available".

Think the latest commit addresses these points.

**Comment by C-Roche** [comment]
Takes a bit of time to run with no info coming back, so I'd put in some outputs like 'Checking Chocolatey...", etc.
Problem with your PS section as it creates the check file even if $ModuleUpdates is empty. You need to change:
$ModuleUpdates | ConvertTo-Json | Out-File -FilePath "$env:temp\powershell-outdated.json" -Encoding utf8 -Force
to
if ($ModuleUpdates) {
            $ModuleUpdates | ConvertTo-Json | Out-File -FilePath "$env:temp\powershell-outdated.json" -Encoding utf8 -Force
        }
You might also consider removing the output files after the script does its work to make sure subsequent runs don't pick them up.

**Comment by danstis** [comment]
> Takes a bit of time to run with no info coming back, so I'd put in some outputs like 'Checking Chocolatey...", etc.
> Problem with your PS section as it creates the check file even if $ModuleUpdates is empty. You need to change:
> $ModuleUpdates | ConvertTo-Json | Out-File -FilePath "$env:temp\powershell-outdated.json" -Encoding utf8 -Force
> to
> if ($ModuleUpdates) {
> $ModuleUpdates | ConvertTo-Json | Out-File -FilePath "$env:temp\powershell-outdated.json" -Encoding utf8 -Force
> }
> You might also consider removing the output files after the script does its work to make sure subsequent runs don't pick them up.

Hmmm, that's intended, I primarily use this to write the files in the temp folder, so I can read them when starting a new console, This is done to give you instant results on launching a new terminal window.
The output from the function is really only there in case it is run manually, but for the most part, I see this running on a scheduled task automatically.

**Comment by C-Roche** [comment]
That's fine, but you probably still don't want it creating empty files. Or if you do, there's no point in checking for the file and then outputting that there are no updates based on whether there's a file there or not.

**Comment by danstis** [comment]
Yeah fair point, I'll update to remove the files before it starts, then check the non-existence as a sign on no updates.

**Comment by C-Roche** [comment]
Looks good to me!

**Pull request merged**
